Fix some broken links
JetBrains/kotlin-spec pull request #34
Opened 2019-07-28 14:56 UTC by eungjun-yi

2019-07-29 14:43 UTC, ice-phoenix requested changes
Thanks a lot for your contribution! If you would be so kind, could you make a few changes to your PR, so that it's even better?

2019-07-29 14:43 UTC, ice-phoenix commented on docs/kotlin.core/overload-resolution.md
> +Determining function applicability for a specific call is a [type constraint][Kotlin Type constraints] problem.
To better follow the capitalization rules, this should be `Kotlin type constraints`

2019-07-29 14:43 UTC, ice-phoenix commented on docs/kotlin.core/overload-resolution.md
> +The selection process uses the [type constraint][Kotlin Type constraints] system of Kotlin, in a way similar to the process of [determining function applicability][Determining function applicability
To better follow the capitalization rules, this should be `Kotlin type constraints`

2019-07-29 14:43 UTC, ice-phoenix commented on docs/kotlin.core/rtti.md
> +- [Class literals][Class literal] and the values they evaluate to
This should link to `Class literals`

2019-07-29 17:32 UTC, eungjun-yi commented
Thanks for your feedback, @ice-phoenix!  I've updated it as you commented.

2019-07-30 09:48 UTC, PetukhovVictor commented
@eungjun-yi also please rebase your branch onto `master`. We recently move a lot of commits to `master` from `dev`.

2019-07-30 15:40 UTC, eungjun-yi commented
Okay, I've done @PetukhovVictor

2020-07-27 13:32 UTC, closed without merging